FROM node:20 AS builder

# Update and upgrade OS packages to fix vulnerabilities
RUN apt-get update && apt-get upgrade -y && apt-get clean

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# --- Stage 2: Nginx para servir os arquivos estáticos ---
FROM nginx:alpine

# Remove o arquivo padrão do nginx
RUN rm -rf /usr/share/nginx/html/*

# Copia o build do Vite para o diretório público do nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Copia um arquivo de configuração customizado do nginx (opcional)
# COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]