version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/clipboard-online
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mongo_data: