FROM node:20

# Update and upgrade OS packages to fix vulnerabilities
RUN apt-get update && apt-get upgrade -y && apt-get clean

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Expose the application port
EXPOSE 3000

# Build the application
RUN npm run build

# Start the application
CMD ["npm", "start"]